### ISSUE TITLE
Cubic Chunks Mod Compatibility

### ISSUE THREAD

**Issue by XBagon** [M4thG33k/TombManyGraves2#20]
The Cubic Chunks mod adds "infinite" height and depth for minecraft worlds. When you die at y>256 it says "A suitable location for the grave wasn't found.". I looked into the code and you use getActualHeight(). Sadly Cubic Chunks returns 256, because it would break portal generation otherwise. Maybe you want to try to use world.isValid(BlockPos pos), it will check if you can place the block for you.

**Comment by XBagon** [comment]
also dying below y=0 will place your grave somewhere y>0

**Comment by M4thG33k** [comment]
I may look into this over the upcoming weekend (I know it's been a while), but I'm not guaranteeing anything. Considering you're the only person who has brought up this compatibility, I may not add it depending on how much work is involved. Regardless, the effect due to dying below y=0 can't change without breaking compatibility with any skyblock.

**Comment by mahtaran** [comment]
https://github.com/M4thG33k/TombManyGraves2/pull/27
I don't know if it works, but I think it should.

**Comment by AstralDestiny** [comment]
I'm Probably not saying this right at all but couldn't you make a check to see if the say Cubic Chunks was running / installed and if so apply a patch to use a new formula instead of how it is now? Just a random thought I don't work in java code so no idea about if it's exactly possible.

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
