### ISSUE TITLE
Dimension Compatibility Progress

### ISSUE THREAD

**Issue by Darkosto** [M4thG33k/TombManyGraves2#21]
Hey M4thG33k!

I'm still having trouble with not getting my death notes 100% of the time in non-vanilla dimensions: Twilight Forest and The Betweenlands. Is it possible I can poke you to check this out? 

I appreciate your time!
Darkosto

**Comment by Darkosto** [comment]
Just to help out, if I may, this may help out :)

The Death List would need to be added back into the inventory in the PlayerDropsEvent as well as in the Clone event

This might help out, too
https://github.com/SleepyTrousers/EnderIO/blob/11e874b89e05008dfd7cf2c25566da4efa1215ff/src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java#L60-L159

Thank you :D

**Comment by xob** [comment]
Hi @M4thG33k,

Looking at the code, there are two places you check for `isRemote` on the world in the `CommonEvents.java` file, which would explain the problem that @Darkosto is observing. His spawn point is in the overworld, he dies in the Twilight Forest and respawns in the overworld, he doesn't get the death note.

Is there a reason for refusing to give the player a death note if he dies and respawns in different dimensions? I would think that removing those two conditions from that file would fix the issue.

If my theory is wrong, I apologize. I only started looking at Minecraft-related code recently, so my understanding of how things work might not be the best.

I would have tried removing the lines of code and doing testing on my end, but I was unable to compile the project because of the missing code from Inventory Pets (or at least, I could not find that code anywhere on the Internet).

Thanks!

**Comment by GoryMoon** [comment]
That isn't the issue, the `isRemote` on world is to see if the world is on the client or server.
If `isRemote` is true the world is the client world, it false it's the server world
