### ISSUE TITLE
Grave breaks and does not drop inventory

### ISSUE THREAD

**Issue by justinrusso** [M4thG33k/TombManyGraves2#35]
When the grave breaks, it should drop its inventory rather than just deleting all items with it.

There are multiple mobs that can cause the grave to break, and rather than just dropping the graves inventory into the world, it just deletes all the items with it.

Reference: https://github.com/DarkPacks/SevTech-Ages/issues/2429

**Comment by M4thG33k** [comment]
The graves are intended to be indestructible. I need to revisit that code since the mechanics must have changed since I originally coded it.

**Comment by justinrusso** [comment]
This also happens with Twilight Forest's Hydra: https://github.com/DarkPacks/SevTech-Ages/issues/1144

**Comment by CorGaming** [comment]
In my case, DarkPacks/SevTech-Ages#2429, the grave simply wasnt created, because I blocked the shoggot with the monolith stone so that they were far way, but let them spit me to dead...when I returned, nothing was there. The first 2 times I died yes, they may have trampled my grave and destroyed it, but the third time I tested it with "trample" protection and still no grave was found.

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
